apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-access-service-v2
  labels:
    app: bank-access-service
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-access-service
      version: v2
  template:
    metadata:
      labels:
        app: bank-access-service
        version: v2
    spec:
      containers:
      - name: bank-access-service
        image: bank-access-service-image-v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}
---