apiVersion: v1
kind: Secret
metadata:
  name: bank-mysql-server-credentials
type: Opaque
data:
  rootpasswd: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: bank-mysql-server
  labels:
    app: bank-mysql-server
    service: bank-mysql-server
spec:
  ports:
  - port: 3306
    name: tcp
  selector:
    app: bank-mysql-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-mysql-server-v1
  labels:
    app: bank-mysql-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-mysql-server
      version: v1
  template:
    metadata:
      labels:
        app: bank-mysql-server
        version: v1
    spec:
      containers:
      - name: bank-mysql-server
        image: bank-mysql-server-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
       
        volumeMounts:
        - name: var-lib-mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: var-lib-mysql
        emptyDir: {}
---