apiVersion: v1
kind: Service
metadata:
  name: bank-redis-server
  labels:
    app: bank-redis-server
    service: bank-redis-server
spec:
  ports:
  - port: 6379
    name: tcp
  selector:
    app: bank-redis-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-redis-server-v1
  labels:
    app: bank-redis-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-redis-server
      version: v1
  template:
    metadata:
      labels:
        app: bank-redis-server
        version: v1
    spec:
      containers:
      - name: bank-redis-server
        image: bank-redis-server-image
        imagePullPolicy: Never
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: var-lib-redis
          mountPath: /var/lib/redis
      volumes:
      - name: var-lib-redis
        emptyDir: {}
---