apiVersion: v1
kind: Service
metadata:
  name: bank-request-processing-service
  labels:
    app: bank-request-processing-service
    service: bank-request-processing-service
spec:
  ports:
  - port: 8084
    name: http
  selector:
    app: bank-request-processing-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bank-request-processing-service
  labels:
    account: bank-request-processing-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-request-processing-service-v1
  labels:
    app: bank-request-processing-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-request-processing-service
      version: v1
  template:
    metadata:
      labels:
        app: bank-request-processing-service
        version: v1
    spec:
      serviceAccountName: bank-request-processing-service
      containers:
      - name: bank-request-processing-service
        image: bank-request-processing-service-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}
---